hash   := $(shell git rev-parse --short HEAD)
type   := mv mz
verts  := src/version.ts
verjs  := 'export const RPGVERSION = "$(hash)" /* autogenerated by Makefile */'
bundle := cheat-engine/www/cheat/init/setup.js

.PHONY: all clean $(type) bundle

all: $(type)

bundle: $(verts)
	pnpm run build

clean:
	-rm *.tar.gz $(verts) $(bundle)

%-$(hash).tar.gz: bundle
	GZIP=-9 COPYFILE_DISABLE=1 tar --exclude='*DS_Store' -czvf $@ \
		-C cheat-engine/www cheat \
		-C _cheat_initialize/$* js
	ln -s -f $@ $*-latest.tar.gz

$(type):%:%-$(hash).tar.gz
	@echo finished packing $@

$(verts):
	echo $(verjs) > $(verts)
