name: Package Sources

on:
  push:
    branches:
      - main
      - ts-rewrite
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: get short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - run: pnpm install
      - name: build and package
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.SHORT_SHA }}.zip
          path: |
            mv-${{ env.SHORT_SHA }}.tar.gz
            mz-${{ env.SHORT_SHA }}.tar.gz
          compression-level: 9
